### ISSUE TITLE
Support request for UE5

### ISSUE THREAD

**Issue by simonSlamka** [TheAshenWolf/WakaTimeForUE4#20]
Hey,

Are you planning on implementing support of UE5 any time soon? I am working on migrating my projects to it and would love to use this plugin!

Thanks

**Comment by Pozitrone** [comment]
Hi! Maybe in the future. Right now UE5 is a highly unstable being and a lot might change.

If I have some free time on my hands and don't know what to do, I might jump on it, but I can't promise anything at the moment.

**Comment by simonSlamka** [comment]
Understandable. Just saying, because more and more people are starting to work in it.

**Comment by RiddMa** [comment]
Looking forward to see this plugin working in UE5

**Comment by simonSlamka** [comment]
> Looking forward to see this plugin working in UE5

+1

**Comment by TheAshenWolf** [comment]
[New release](https://github.com/TheAshenWolf/WakaTimeForUE4/releases/tag/1.2.2) here! Included also UE5 version :)
Please, try it out and give me a word if you encounter any issues!
